Vagrant.configure("2") do |config|
    config.vm.box = "fgrehm/trusty64-lxc"
    config.vm.provider "lxc"
    config.vm.define "web" do |web|
      web.vm.provision "shell", path: "scripts/apache-install.sh"
      web.vm.provision "file", source: "configs/apache-example.site",
        destination: "/tmp/configs/apache-example.site"
      web.vm.provision "shell", path: "scripts/apache-sites.sh"
    end
    config.vm.define "db" do |db|
      db.vm.provision "shell", path: "scripts/mysql-install.sh"
    end
  end
