 Vagrant.configure("2") do |config|
  config.vm.box = "btkien/ubuntu-1804-k8s-advance"
  config.vm.box_version = "1.0.0"
  config.ssh.username = 'aen'
  config.vm.box_check_update = false

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "c1-cp1" do |master|
    master.vm.box_check_update = false
    master.vm.hostname = "c1-cp1"
    master.vm.network :private_network, ip: "192.168.56.10"
  end
  (1..3).each do |i|
    config.vm.define "c1-node#{i}" do |node|
      node.vm.box_check_update = false
      node.vm.hostname = "c1-node#{i}"
      node.vm.network :private_network, ip: "192.168.56.1#{i}"
    end
  end
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo swapoff -a
  #   sudo systemctl restart kubelet
  # SHELL
end
